# Configuration file for dev environment. Will apply to all functions, but will be overwritten by
# configurations files in specific function folder.
#data_set_id: 4972094093286445
description: "This function does an important job. Yes :doge:"
